// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhlfgtfgbbmqxynhlxvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZobGZndGZnYmJtcXh5bmhseHZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MDM5MjgsImV4cCI6MjA2OTE3OTkyOH0.M_u7dDEWlNfpXOcGYzOd-VjTmLm3xmdqCuh0fiohook";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});